1、捕获异常的方法
>- try...catch...finally
> >- try块包含的代码组成了程序的正常操作部分，但这部分程序可能遇到某些严重的错误；
> >- catch块包含的代码处理各种错误情况，这些错误是执行try块中的代码时遇到的。这个块还可以用于记录错误；
> >- finally块包含的代码清理资源或执行通常要在try块或catch块末尾执行的其他操作。无论是否抛出异常，都会执行finally块。

2、多个catch块的执行顺序
> 当在try中抛出异常之后，程序会只执行它在可用的catch块列表中找到的第一个合适的catch块。所以，我们在编写这样的结构时，最先编写的是用于处理非常特殊的错误情况，接着是比较一般的块。

3、System.Exception属性
> 属性 | 说明
> ---|---
> Data | 给异常添加键/值语句，以提供关于异常的额外信息
> HelpLink | 链接到一个帮助文档上，以提供关于该异常的更多信息
> InnerException | 如果异常是在catch块中抛出的，他就会包含把代码发送到catch块中的异常对象
> Message | 描述错误情况的文本
> Source | 导致异常的应用程序或对象名
> StackTrace | 栈上方法调用的详细信息，有助于跟踪抛出异常的方法

4、异常过滤器
> 异常过滤器是C#6的一个新特性。我们可以设置异常的ErrorCode，在catch块中使用when关键字过滤出相应的ErrorCode的异常。这样做的好处是可以使用多个处理程序来处理相同的异常类型。
> ```
>     public static void ThrowWithErrorCode(int code)
>     {
>         thorw new MyCustomException("Error in Foo")
>         {
>             ErrorCode = code;
>         }
>     }
>   //使用ErrorCode
>     try
>     {
>         ThrowWithErrorCode(405);
>     }
>     catch(MyCustomException ex) when (ex.ErrorCode == 405)
>     {
>         WriteLine($"Exception caught with filter {ex.Message} and {ex.ErrorCode}");
>     }
> ```

5、如果没有代码块处理异常，程序会停止么
> 代码中没有catch块可以处理异常的时候，.NET运行库会捕获它。出现这样的情况，程序流会退出程序，由.NET运行库中的catch块捕获它。
